apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'hello'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'secret-k8s/data/database/config'
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "secret-k8s/data/database/config" -}}
          postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
          {{- end -}}
      labels:
        app: hello
    spec:
      serviceAccountName: hello
      containers:
        - name: main
          image: ondrejsika/serve
          ports:
            - containerPort: 80
