apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: example
  namespace: default
spec:
  vaultAuthRef: auth
  refreshAfter: 30s

  type: kv-v2
  mount: test
  path: example

  destination:
    name: example
    create: true
