apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: auth
  namespace: default
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: test-read
    serviceAccount: default
    audiences:
      - vault
